source 'https://rubygems.org'

gem 'activerecord', '~> 7.0.3', require: 'active_record'
gem 'activesupport', require: %w[active_support/dependencies]
gem 'zeitwerk', '~> 2.5.4'

group :development do
    gem 'sqlite3'  # run `apk add sqlite-dev` first
end
